name: linter

on: push

jobs:
  build:
    
    runs-on: ubuntu-latest
    
    steps:
      - name: Install npm packges
        run: |
          make install
      - name: Start inner project linter
        run: |
          make lint
